#pragma once

#include "lumen_driver_abi.h"

#include <iddcx.h>
#include <wdf.h>

struct LumenDeviceContext {
  LumenDriverCoreState core_state;
  WDFQUEUE access_unit_queue;
  WDFQUEUE event_queue;
};

WDF_DECLARE_CONTEXT_TYPE_WITH_NAME(LumenDeviceContext, LumenGetDeviceContext);

EVT_WDF_DRIVER_DEVICE_ADD LumenEvtDeviceAdd;
EVT_WDF_DEVICE_FILE_CREATE LumenEvtDeviceFileCreate;
EVT_WDF_FILE_CLEANUP LumenEvtFileCleanup;
EVT_WDF_IO_QUEUE_IO_DEVICE_CONTROL LumenEvtIoDeviceControl;
EVT_WDF_IO_QUEUE_IO_CANCELED_ON_QUEUE LumenEvtIoCancelledOnQueue;
EVT_IDD_CX_PARSE_MONITOR_DESCRIPTION LumenEvtIddCxParseMonitorDescription;
EVT_IDD_CX_ADAPTER_INIT_FINISHED LumenEvtIddCxAdapterInitFinished;
EVT_IDD_CX_ADAPTER_COMMIT_MODES LumenEvtIddCxAdapterCommitModes;
EVT_IDD_CX_MONITOR_GET_DEFAULT_DESCRIPTION_MODES LumenEvtIddCxMonitorGetDefaultDescriptionModes;
EVT_IDD_CX_MONITOR_QUERY_TARGET_MODES LumenEvtIddCxMonitorQueryTargetModes;
EVT_IDD_CX_MONITOR_ASSIGN_SWAPCHAIN LumenEvtIddCxMonitorAssignSwapChain;
EVT_IDD_CX_MONITOR_UNASSIGN_SWAPCHAIN LumenEvtIddCxMonitorUnassignSwapChain;

uint64_t LumenOwnerId(WDFFILEOBJECT file_object);
LumenDriverCoreRequest LumenRequest(uint32_t operation, uint64_t owner_id, uint64_t generation);
NTSTATUS LumenStatusToNtStatus(uint32_t status);
