#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


FIXTURE_PATH = Path("docs/protocol/lumen-protocol-conformance.json")
CPP_OUTPUT_PATH = Path("src/lumen_protocol_control_wire_generated.h")
SWIFT_OUTPUT_PATH = Path(
    "src/platform/macos/Projects/LumenMacBridge/Sources/Generated/"
    "LumenProtocolControlWireLayout.generated.swift"
)


def load_fixture(root: Path) -> dict[str, Any]:
    return json.loads((root / FIXTURE_PATH).read_text())


def control_wire(fixture: dict[str, Any]) -> dict[str, Any]:
    value = fixture.get("controlWire")
    if not isinstance(value, dict):
        raise ValueError("Fixture is missing controlWire")
    return value


def hex_u16(value: int) -> str:
    return f"0x{value:04X}".lower().replace("x", "x")


def cpp_offset_expression(header_size: int, offset: int) -> str:
    if offset == header_size:
        return "header_size"
    return f"header_size + {offset - header_size}"


def render_cpp(control: dict[str, Any]) -> str:
    header_size = int(control["headerSize"])
    hdr = control["hdrFrameState"]
    hdr_flags = hdr["flags"]
    hdr_offsets = hdr["offsets"]
    encoded = control["encodedTileFrameState"]
    encoded_flags = encoded["flags"]
    encoded_offsets = encoded["offsets"]

    return f"""/**
 * @file src/lumen_protocol_control_wire_generated.h
 * @brief Generated Lumen control wire constants.
 *
 * Generated by tools/protocol/generate_lumen_protocol.py.
 * Do not edit by hand; edit docs/protocol/lumen-protocol-conformance.json.
 */
#pragma once

#include <cstddef>
#include <cstdint>

namespace lumen::protocol::control {{
  inline constexpr std::uint16_t hdr_frame_state_type = {hex_u16(int(hdr["packetType"]))};
  inline constexpr std::uint16_t encoded_tile_frame_state_type = {hex_u16(int(encoded["packetType"]))};

  inline constexpr std::uint8_t hdr_frame_state_version = {int(hdr["version"])};
  inline constexpr std::uint8_t hdr_frame_state_flag_has_static_metadata = {int(hdr_flags["hasStaticMetadata"])};
  inline constexpr std::uint8_t hdr_frame_state_flag_has_overlay_regions = {int(hdr_flags["hasOverlayRegions"])};
  inline constexpr std::uint8_t hdr_overlay_region_flag_has_metadata = {int(hdr_flags["overlayRegionHasMetadata"])};

  inline constexpr std::uint8_t encoded_tile_frame_state_version = {int(encoded["version"])};
  inline constexpr std::uint8_t encoded_tile_frame_state_flag_has_tile_region = {int(encoded_flags["hasTileRegion"])};

  inline constexpr std::size_t header_size = {header_size};

  inline constexpr std::size_t hdr_frame_state_version_offset = {cpp_offset_expression(header_size, int(hdr_offsets["version"]))};
  inline constexpr std::size_t hdr_frame_state_dynamic_range_offset = {cpp_offset_expression(header_size, int(hdr_offsets["frameDynamicRange"]))};
  inline constexpr std::size_t hdr_frame_state_flags_offset = {cpp_offset_expression(header_size, int(hdr_offsets["flags"]))};
  inline constexpr std::size_t hdr_frame_state_effective_frame_offset = {cpp_offset_expression(header_size, int(hdr_offsets["effectiveFromFrameNumber"]))};
  inline constexpr std::size_t hdr_frame_state_overlay_region_count_offset = {cpp_offset_expression(header_size, int(hdr_offsets["overlayRegionCount"]))};
  inline constexpr std::size_t hdr_frame_state_static_metadata_offset = {cpp_offset_expression(header_size, int(hdr_offsets["staticMetadata"]))};

  inline constexpr std::size_t encoded_tile_frame_state_packet_length = {int(encoded["packetLength"])};
  inline constexpr std::size_t encoded_tile_frame_state_payload_length = {int(encoded["payloadLength"])};
  inline constexpr std::size_t encoded_tile_frame_state_version_offset = {cpp_offset_expression(header_size, int(encoded_offsets["version"]))};
  inline constexpr std::size_t encoded_tile_frame_state_flags_offset = {cpp_offset_expression(header_size, int(encoded_offsets["flags"]))};
  inline constexpr std::size_t encoded_tile_frame_state_effective_frame_offset = {cpp_offset_expression(header_size, int(encoded_offsets["effectiveFromFrameNumber"]))};
  inline constexpr std::size_t encoded_tile_frame_state_group_id_offset = {cpp_offset_expression(header_size, int(encoded_offsets["frameGroupId"]))};
  inline constexpr std::size_t encoded_tile_frame_state_tile_index_offset = {cpp_offset_expression(header_size, int(encoded_offsets["tileIndex"]))};
  inline constexpr std::size_t encoded_tile_frame_state_tile_count_offset = {cpp_offset_expression(header_size, int(encoded_offsets["tileCount"]))};
  inline constexpr std::size_t encoded_tile_frame_state_lane_index_offset = {cpp_offset_expression(header_size, int(encoded_offsets["encodedLaneIndex"]))};
  inline constexpr std::size_t encoded_tile_frame_state_lane_count_offset = {cpp_offset_expression(header_size, int(encoded_offsets["encodedLaneCount"]))};
  inline constexpr std::size_t encoded_tile_frame_state_tile_origin_x_offset = {cpp_offset_expression(header_size, int(encoded_offsets["tileOriginX"]))};
  inline constexpr std::size_t encoded_tile_frame_state_tile_origin_y_offset = {cpp_offset_expression(header_size, int(encoded_offsets["tileOriginY"]))};
  inline constexpr std::size_t encoded_tile_frame_state_tile_width_offset = {cpp_offset_expression(header_size, int(encoded_offsets["tileWidth"]))};
  inline constexpr std::size_t encoded_tile_frame_state_tile_height_offset = {cpp_offset_expression(header_size, int(encoded_offsets["tileHeight"]))};
}}  // namespace lumen::protocol::control
"""


def swift_offset_expression(header_size_name: str, header_size: int, offset: int) -> str:
    if offset == header_size:
        return header_size_name
    return f"{header_size_name} + {offset - header_size}"


def render_swift(control: dict[str, Any]) -> str:
    header_size = int(control["headerSize"])
    hdr = control["hdrFrameState"]
    hdr_flags = hdr["flags"]
    hdr_offsets = hdr["offsets"]
    encoded = control["encodedTileFrameState"]
    encoded_flags = encoded["flags"]
    encoded_offsets = encoded["offsets"]
    header_name = "LumenProtocolControlWireLayout.headerSize"

    return f"""// Generated by tools/protocol/generate_lumen_protocol.py.
// Do not edit by hand; edit docs/protocol/lumen-protocol-conformance.json.

public enum LumenProtocolControlWireLayout {{
    public static let headerSize: UInt16 = {header_size}

    public enum HDRFrameState {{
        public static let packetType: UInt16 = {hex_u16(int(hdr["packetType"]))}
        public static let version: UInt8 = {int(hdr["version"])}

        public enum Flags {{
            public static let hasStaticMetadata: UInt8 = {int(hdr_flags["hasStaticMetadata"])}
            public static let hasOverlayRegions: UInt8 = {int(hdr_flags["hasOverlayRegions"])}
        }}

        public enum OverlayRegionFlags {{
            public static let hasMetadata: UInt8 = {int(hdr_flags["overlayRegionHasMetadata"])}
        }}

        public enum Offsets {{
            public static let version: UInt16 = {swift_offset_expression(header_name, header_size, int(hdr_offsets["version"]))}
            public static let frameDynamicRange: UInt16 = {swift_offset_expression(header_name, header_size, int(hdr_offsets["frameDynamicRange"]))}
            public static let flags: UInt16 = {swift_offset_expression(header_name, header_size, int(hdr_offsets["flags"]))}
            public static let effectiveFromFrameNumber: UInt16 = {swift_offset_expression(header_name, header_size, int(hdr_offsets["effectiveFromFrameNumber"]))}
            public static let overlayRegionCount: UInt16 = {swift_offset_expression(header_name, header_size, int(hdr_offsets["overlayRegionCount"]))}
            public static let staticMetadata: UInt16 = {swift_offset_expression(header_name, header_size, int(hdr_offsets["staticMetadata"]))}
        }}
    }}

    public enum EncodedTileFrameState {{
        public static let packetType: UInt16 = {hex_u16(int(encoded["packetType"]))}
        public static let version: UInt8 = {int(encoded["version"])}
        public static let packetLength: UInt16 = {int(encoded["packetLength"])}
        public static let payloadLength: UInt16 = {int(encoded["payloadLength"])}

        public enum Flags {{
            public static let hasTileRegion: UInt8 = {int(encoded_flags["hasTileRegion"])}
        }}

        public enum Offsets {{
            public static let version: UInt16 = {swift_offset_expression(header_name, header_size, int(encoded_offsets["version"]))}
            public static let flags: UInt16 = {swift_offset_expression(header_name, header_size, int(encoded_offsets["flags"]))}
            public static let effectiveFromFrameNumber: UInt16 = {swift_offset_expression(header_name, header_size, int(encoded_offsets["effectiveFromFrameNumber"]))}
            public static let frameGroupId: UInt16 = {swift_offset_expression(header_name, header_size, int(encoded_offsets["frameGroupId"]))}
            public static let tileIndex: UInt16 = {swift_offset_expression(header_name, header_size, int(encoded_offsets["tileIndex"]))}
            public static let tileCount: UInt16 = {swift_offset_expression(header_name, header_size, int(encoded_offsets["tileCount"]))}
            public static let encodedLaneIndex: UInt16 = {swift_offset_expression(header_name, header_size, int(encoded_offsets["encodedLaneIndex"]))}
            public static let encodedLaneCount: UInt16 = {swift_offset_expression(header_name, header_size, int(encoded_offsets["encodedLaneCount"]))}
            public static let tileOriginX: UInt16 = {swift_offset_expression(header_name, header_size, int(encoded_offsets["tileOriginX"]))}
            public static let tileOriginY: UInt16 = {swift_offset_expression(header_name, header_size, int(encoded_offsets["tileOriginY"]))}
            public static let tileWidth: UInt16 = {swift_offset_expression(header_name, header_size, int(encoded_offsets["tileWidth"]))}
            public static let tileHeight: UInt16 = {swift_offset_expression(header_name, header_size, int(encoded_offsets["tileHeight"]))}
        }}
    }}
}}
"""


def write_if_changed(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text() == text:
        return
    path.write_text(text)


def generate(root: Path) -> None:
    root = root.resolve()
    fixture = load_fixture(root)
    control = control_wire(fixture)
    write_if_changed(root / CPP_OUTPUT_PATH, render_cpp(control))
    write_if_changed(root / SWIFT_OUTPUT_PATH, render_swift(control))


def generated_outputs(root: Path) -> dict[Path, str]:
    root = root.resolve()
    fixture = load_fixture(root)
    control = control_wire(fixture)
    return {
        CPP_OUTPUT_PATH: render_cpp(control),
        SWIFT_OUTPUT_PATH: render_swift(control),
    }


def find_stale_outputs(root: Path) -> list[Path]:
    root = root.resolve()
    stale: list[Path] = []
    for relative_path, expected in generated_outputs(root).items():
        path = root / relative_path
        if not path.exists() or path.read_text() != expected:
            stale.append(relative_path)
    return stale


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Lumen protocol authority files.")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--check", action="store_true", help="Fail if generated protocol files are stale.")
    args = parser.parse_args()
    if args.check:
        stale = find_stale_outputs(args.root)
        for path in stale:
            print(f"stale generated file: {path}")
        return 1 if stale else 0

    generate(args.root)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
